### ISSUE TITLE
Blesta CMS plugin does not appear in 'Available' list

### ISSUE THREAD

**Issue by komputronika** [licensecart/BlestaCMS#4]
Hello, 

I copied all the files to the `plugins/blesta_cms` folder, but the **Blesta CMS** plugin does not appear in the `Settings> Company> Plugins> Available` list

Please let me know on how to update that list.

Thanks

**Comment by atlanical** [comment]
Hi it depends on what you've uploaded ensure the structure is perfect. So inside the blesta_cms folder you see the files in this github. 

Otherwise if you've got a paid license contact us at https://blesta.store/plugin/support/validate

Or contact our team for Complimentary support code: https://blesta.store/plugin/support/complimentary

**Comment by atlanical** [comment]
May be linked to the line 0 bug found by Tyson.

**Comment by pixelpaulaus** [comment]
installed, cleared cache and nothing shows.
I installed just as instructed.
